<template>
    <!-- <div class="select">
        <el-select v-model="selectedValue" placeholder="请选择原料">
          <el-option :label="土豆" :value="potato"></el-option>
          <el-option :label="牛肉" :value="beef"></el-option>
          <el-option :label="辣椒" :value="pepper"></el-option>
          此处接入数据库各项原料
        </el-select>
    </div> -->
    <!-- <div class="list">
        <div class="raw_material">
          <el-table :data="tableData" style="width: 100%">
            呈现原料的列表
            <el-table-column prop="name" label="name" width="180" />
            <el-table-column prop="vender" label="vender" width="180" />
            <el-table-column prop="rating" label="rating" width="180"/>
          </el-table>
        </div>
      </div> -->
</template>

<script setup>
// const tableData = [
//   {
//     name: 'potato',
//     vender: 'XX COMPANY',
//     rating: 'GOOD',
//   },
// ];  
</script>